{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "\"\"\"\n",
    "Hybrid Quantum Physics-Informed Neural Network (QPINN)\n",
    "for 2D Crystal Growth with Phase-Field Model\n",
    "\n",
    "------------------------------------------------------\n",
    "Features:\n",
    "- Navier–Stokes + solute transport\n",
    "- Phase-field crystal growth\n",
    "- Stefan condition at solid–liquid interface\n",
    "- Anisotropic surface energy\n",
    "- Adaptive sampling near interface\n",
    "- Quantum layer executed via IBM Qiskit Runtime Estimator\n",
    "- SPSA optimizer for hardware efficiency\n",
    "- Designed for 4-qubit IBM backend\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Mathematical Formulation of the Hybrid Quantum PINN for Time-Dependent Crystal Growth\n",
    "\n",
    "## 1. Problem Setting\n",
    "\n",
    "We consider **time-dependent crystal growth** in a two-dimensional spatial domain (\\Omega \\subset \\mathbb{R}^2), governed by a **phase-field model coupled to flow and solute transport**. The solution fields are:\n",
    "\n",
    "[\n",
    "\\mathbf{u}(x,y,t) = (u,v), \\quad\n",
    "p(x,y,t), \\quad\n",
    "c(x,y,t), \\quad\n",
    "\\phi(x,y,t)\n",
    "]\n",
    "\n",
    "where:\n",
    "\n",
    "* (\\mathbf{u}): velocity field,\n",
    "* (p): pressure,\n",
    "* (c): solute concentration,\n",
    "* (\\phi): phase-field variable\n",
    "  ((\\phi \\approx +1): solid, (\\phi \\approx -1): liquid).\n",
    "\n",
    "---\n",
    "\n",
    "## 2. Hybrid Quantum PINN Approximation\n",
    "\n",
    "The solution is approximated by a **hybrid classical–quantum neural network**:\n",
    "\n",
    "[\n",
    "(u, v, p, c, \\phi)\n",
    "==================\n",
    "\n",
    "\\mathcal{N}_{\\theta_c, \\theta_q}(x, y, t)\n",
    "]\n",
    "\n",
    "where:\n",
    "\n",
    "* (\\theta_c): classical network parameters,\n",
    "* (\\theta_q): quantum circuit parameters.\n",
    "\n",
    "The quantum component computes an expectation value:\n",
    "\n",
    "[\n",
    "f_q(\\mathbf{z}) = \\langle \\psi(\\mathbf{z}, \\theta_q) | \\hat{O} | \\psi(\\mathbf{z}, \\theta_q) \\rangle\n",
    "]\n",
    "\n",
    "with (\\hat{O} = Z^{\\otimes n}) and (\\mathbf{z}) classical features.\n",
    "\n",
    "---\n",
    "\n",
    "## 3. Phase-Field Free Energy and Chemical Potential\n",
    "\n",
    "The **free energy functional** is:\n",
    "\n",
    "[\n",
    "\\mathcal{F}[\\phi, c]\n",
    "====================\n",
    "\n",
    "\\int_\\Omega\n",
    "\\left[\n",
    "\\frac{\\epsilon(\\theta)^2}{2} |\\nabla \\phi|^2\n",
    "+\n",
    "\\frac{1}{4}(\\phi^2 - 1)^2\n",
    "+\n",
    "\\lambda_c c (1 - \\phi^2)\n",
    "\\right] d\\Omega\n",
    "]\n",
    "\n",
    "The **chemical potential** is:\n",
    "\n",
    "[\n",
    "\\mu\n",
    "===\n",
    "\n",
    "-\\nabla \\cdot \\left( \\epsilon(\\theta)^2 \\nabla \\phi \\right)\n",
    "+\n",
    "\\phi(\\phi^2 - 1)\n",
    "----------------\n",
    "\n",
    "2 \\lambda_c c \\phi\n",
    "]\n",
    "\n",
    "---\n",
    "\n",
    "## 4. Anisotropic Surface Energy\n",
    "\n",
    "The surface energy depends on the interface orientation:\n",
    "\n",
    "[\n",
    "\\epsilon(\\theta)\n",
    "================\n",
    "\n",
    "\\epsilon_0 \\left( 1 + \\delta \\cos(m \\theta) \\right),\n",
    "\\quad\n",
    "\\theta = \\arctan\\left(\\frac{\\phi_y}{\\phi_x}\\right)\n",
    "]\n",
    "\n",
    "This anisotropy induces faceted crystal growth.\n",
    "\n",
    "---\n",
    "\n",
    "## 5. Time-Dependent Phase-Field Evolution\n",
    "\n",
    "The **phase-field evolution equation** is:\n",
    "\n",
    "[\n",
    "\\partial_t \\phi\n",
    "+\n",
    "\\mathbf{u} \\cdot \\nabla \\phi\n",
    "============================\n",
    "\n",
    "* M\n",
    "  \\left(\n",
    "  \\mu\n",
    "*\n",
    "\n",
    "\\lambda_T (c - c_m) |\\nabla \\phi|\n",
    "\\right)\n",
    "]\n",
    "\n",
    "where:\n",
    "\n",
    "* (M): interface mobility,\n",
    "* (\\lambda_T): Stefan coupling coefficient,\n",
    "* (c_m): equilibrium concentration.\n",
    "\n",
    "---\n",
    "\n",
    "## 6. Solute Transport Equation\n",
    "\n",
    "[\n",
    "\\partial_t c\n",
    "+\n",
    "\\mathbf{u} \\cdot \\nabla c\n",
    "=========================\n",
    "\n",
    "D \\nabla^2 c\n",
    "]\n",
    "\n",
    "where (D) is the solute diffusivity.\n",
    "\n",
    "---\n",
    "\n",
    "## 7. Stefan Condition (Interface Constraint)\n",
    "\n",
    "At the solid–liquid interface ((\\phi \\approx 0)), the **Stefan condition** is enforced via the residual:\n",
    "\n",
    "[\n",
    "\\mathcal{R}_{\\text{Stefan}}\n",
    "===========================\n",
    "\n",
    "## \\mu\n",
    "\n",
    "\\lambda_T (c - c_m) |\\nabla \\phi|\n",
    "]\n",
    "\n",
    "This balances latent heat release with interface motion.\n",
    "\n",
    "---\n",
    "\n",
    "## 8. Physics-Informed Loss Function\n",
    "\n",
    "The **physics loss** is defined as the mean-squared residual:\n",
    "\n",
    "[\n",
    "\\mathcal{L}_{\\text{PDE}}\n",
    "========================\n",
    "\n",
    "\\left\\langle\n",
    "\\left(\n",
    "\\partial_t \\phi\n",
    "+\n",
    "\\mathbf{u} \\cdot \\nabla \\phi\n",
    "+\n",
    "M (\\mu - \\lambda_T c |\\nabla \\phi|)\n",
    "\\right)^2\n",
    "+\n",
    "\\left(\n",
    "\\partial_t c\n",
    "+\n",
    "\\mathbf{u} \\cdot \\nabla c\n",
    "-------------------------\n",
    "\n",
    "D \\nabla^2 c\n",
    "\\right)^2\n",
    "\\right\\rangle\n",
    "]\n",
    "\n",
    "---\n",
    "\n",
    "## 9. FEM Data Validation Loss\n",
    "\n",
    "Given reference finite-element data\n",
    "((x_i, y_i, t_i, u_i, v_i, p_i, c_i, \\phi_i)),\n",
    "a supervised validation term is added:\n",
    "\n",
    "[\n",
    "\\mathcal{L}_{\\text{FEM}}\n",
    "========================\n",
    "\n",
    "\\frac{1}{N}\n",
    "\\sum_{i=1}^N\n",
    "|\n",
    "\\mathcal{N}(x_i,y_i,t_i)\n",
    "------------------------\n",
    "\n",
    "(u_i,v_i,p_i,c_i,\\phi_i)\n",
    "|^2\n",
    "]\n",
    "\n",
    "---\n",
    "\n",
    "## 10. Total Training Objective\n",
    "\n",
    "[\n",
    "\\mathcal{L}\n",
    "===========\n",
    "\n",
    "\\mathcal{L}*{\\text{PDE}}\n",
    "+\n",
    "\\alpha \\mathcal{L}*{\\text{FEM}}\n",
    "]\n",
    "\n",
    "with weighting factor (\\alpha > 0).\n",
    "\n",
    "---\n",
    "\n",
    "## 11. Quantum Shot-Noise Model\n",
    "\n",
    "Quantum expectation values are estimated from (S) measurement shots:\n",
    "\n",
    "[\n",
    "\\hat{f}_S\n",
    "=========\n",
    "\n",
    "\\frac{1}{S} \\sum_{k=1}^S z_k,\n",
    "\\quad z_k \\in {-1, +1}\n",
    "]\n",
    "\n",
    "with variance:\n",
    "\n",
    "[\n",
    "\\mathrm{Var}[\\hat{f}_S]\n",
    "=======================\n",
    "\n",
    "\\frac{1 - \\langle Z \\rangle^2}{S}\n",
    ";\\le;\n",
    "\\frac{1}{S}\n",
    "]\n",
    "\n",
    "---\n",
    "\n",
    "## 12. Uncertainty Quantification via Monte-Carlo Sampling\n",
    "\n",
    "Shot-noise uncertainty is estimated by repeated circuit execution:\n",
    "\n",
    "[\n",
    "\\mu_f(x)\n",
    "========\n",
    "\n",
    "\\frac{1}{K} \\sum_{k=1}^K f^{(k)}(x),\n",
    "\\quad\n",
    "\\sigma_f^2(x)\n",
    "=============\n",
    "\n",
    "\\frac{1}{K-1} \\sum_{k=1}^K (f^{(k)}(x) - \\mu_f(x))^2\n",
    "]\n",
    "\n",
    "This propagates through the PINN to produce:\n",
    "\n",
    "[\\phi(x,y,t) \\pm \\sigma_\\phi(x,y,t),\\quad \\mathcal{R}(x,y,t) \\pm \\sigma_{\\mathcal{R}}(x,y,t)]\n",
    "\n",
    "---\n",
    "\n",
    "## 13. Noise-Aware Training Criterion\n",
    "\n",
    "Training is terminated when improvements fall below the shot-noise floor:\n",
    "\n",
    "[\n",
    "\\Delta \\mathcal{L}\n",
    "<\n",
    "k , \\sigma_{\\mathcal{L}}\n",
    "\\quad (k \\approx 2)\n",
    "]\n",
    "\n",
    "ensuring computational resources are not wasted in a noise-dominated regime.\n",
    "\n",
    "---\n",
    "\n",
    "## 14. Summary of Key Contributions\n",
    "\n",
    "* Hybrid quantum–classical PINN for moving-interface PDEs\n",
    "* Phase-field crystal growth with anisotropy and Stefan condition\n",
    "* Time-dependent physics-informed learning\n",
    "* Direct uncertainty quantification from quantum measurement statistics\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
